export const CONFIGURATION_RESPONSE_MAX_BYTES = 65_536;
export const SNAPSHOT_FRAME_MAX_BYTES = 2_097_152;
export const SNAPSHOT_PLAYER_LIMIT = 4_096;
export const SNAPSHOT_WEBSOCKET_SUBPROTOCOL = 'blob-royale.snapshot.v1';

export const CONFIGURATION_ENDPOINT_PATH = '/api/v1/config';
export const SNAPSHOT_ENDPOINT_PATH = '/api/v1/snapshots';

export const RECONNECT_BACKOFF_MILLISECONDS = Object.freeze([
  1_000, 2_000, 4_000, 8_000, 16_000, 16_000,
] as const);
export const CONFIGURATION_FETCH_TIMEOUT_MILLISECONDS = 10_000;
export const WEBSOCKET_CONNECT_TIMEOUT_MILLISECONDS = 10_000;

export const CANVAS_MAX_WIDTH_PIXELS = 960;
export const CANVAS_MAX_HEIGHT_PIXELS = 640;
export const DEBUG_PLAYER_ROW_LIMIT = 100;
