#!/usr/bin/env node
// Generates the browser's immutable TypeScript boundary and bundled validation
// schemas from the canonical local protocol v1 schemas. With --check it writes
// nothing and fails on drift; without arguments it deterministically rewrites
// both generated files. The operation is idempotent.

import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { compile } from 'json-schema-to-typescript';
import { format as formatWithPrettier } from 'prettier';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const webRoot = resolve(scriptDirectory, '..');
const schemaRoot = resolve(webRoot, '../docs/protocol/schema/v1');
const generatedRoot = resolve(webRoot, 'src/features/simulation/generated');
const generatedTypesPath = resolve(
  generatedRoot,
  'protocolV1Types.generated.ts',
);
const generatedSchemasPath = resolve(
  generatedRoot,
  'protocolV1Schemas.generated.ts',
);

const rootSchemaFileNames = Object.freeze([
  'configuration-response.schema.json',
  'error-response.schema.json',
  'liveness-response.schema.json',
  'readiness-response.schema.json',
  'snapshot-message.schema.json',
]);

const generatedHeader = `// @generated by scripts/generateProtocolV1Types.mjs.
// Canonical source: ../../../../../docs/protocol/schema/v1/*.schema.json.
// Do not edit this file directly; run npm run generate:protocol.

`;

function parseArguments(argumentsToParse) {
  if (argumentsToParse.length === 0) {
    return Object.freeze({ checkOnly: false });
  }

  if (argumentsToParse.length === 1 && argumentsToParse[0] === '--check') {
    return Object.freeze({ checkOnly: true });
  }

  throw new Error(
    `WEB.PROTOCOL_TYPE_GENERATOR_ARGUMENT_INVALID: expected no arguments or --check, received ${argumentsToParse.join(' ')}`,
  );
}

async function readCanonicalSchemas() {
  const schemaFileNames = (await readdir(schemaRoot, { withFileTypes: true }))
    .filter(
      (directoryEntry) =>
        directoryEntry.isFile() && directoryEntry.name.endsWith('.schema.json'),
    )
    .map((directoryEntry) => directoryEntry.name)
    .sort();
  if (schemaFileNames.length === 0) {
    throw new Error(
      `WEB.PROTOCOL_SCHEMAS_MISSING: no canonical schemas found in ${schemaRoot}`,
    );
  }

  return Promise.all(
    schemaFileNames.map(async (schemaFileName) => {
      const schemaText = await readFile(
        resolve(schemaRoot, schemaFileName),
        'utf8',
      );
      return Object.freeze({
        schemaFileName,
        schema: JSON.parse(schemaText),
      });
    }),
  );
}

async function generateTypes() {
  const aggregateSchema = {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    title: 'ProtocolV1SchemaTypes',
    type: 'object',
    additionalProperties: false,
    required: rootSchemaFileNames.map((schemaFileName) =>
      schemaFileName.replace('.schema.json', '').replaceAll('-', '_'),
    ),
    properties: Object.fromEntries(
      rootSchemaFileNames.map((schemaFileName) => [
        schemaFileName.replace('.schema.json', '').replaceAll('-', '_'),
        { $ref: schemaFileName },
      ]),
    ),
  };

  // json-schema-to-typescript 15.0.4 exposes no immutableTypes option. Keep
  // immutability as a deterministic post-generation transform until the exact
  // pinned generator publishes that supported option.
  const mutableTypes = await compile(aggregateSchema, 'ProtocolV1SchemaTypes', {
    additionalProperties: false,
    bannerComment: '',
    cwd: schemaRoot,
    declareExternallyReferenced: true,
    enableConstEnums: false,
    ignoreMinAndMaxItems: false,
    style: {
      bracketSpacing: true,
      printWidth: 80,
      semi: true,
      singleQuote: true,
      tabWidth: 2,
      trailingComma: 'all',
      useTabs: false,
    },
    strictIndexSignatures: true,
    unreachableDefinitions: true,
    unknownAny: true,
  });

  const declarationNames = Array.from(
    mutableTypes.matchAll(/^export (?:interface|type|enum) ([A-Za-z0-9_]+)/gm),
    (match) => match[1],
  );

  if (declarationNames.length === 0) {
    throw new Error(
      'WEB.PROTOCOL_TYPE_GENERATION_EMPTY: schema compiler emitted no declarations',
    );
  }

  const mutableDeclarations = mutableTypes.replace(
    /^export (interface|type|enum) /gm,
    '$1 Mutable',
  );
  const renamedReferences = declarationNames.reduce(
    (source, declarationName) =>
      source.replaceAll(
        new RegExp(`\\b${declarationName}\\b`, 'g'),
        `Mutable${declarationName}`,
      ),
    mutableDeclarations,
  );
  const readonlyAliases = declarationNames
    .map(
      (declarationName) =>
        `export type ${declarationName} = DeepReadonly<Mutable${declarationName}>;`,
    )
    .join('\n');

  return formatWithPrettier(
    `${generatedHeader}type DeepReadonly<T> = T extends (...arguments_: readonly unknown[]) => unknown
  ? T
  : T extends readonly (infer Item)[]
    ? readonly DeepReadonly<Item>[]
    : T extends object
      ? { readonly [Key in keyof T]: DeepReadonly<T[Key]> }
      : T;

${renamedReferences.trim()}

${readonlyAliases}
`,
    {
      parser: 'typescript',
      singleQuote: true,
      trailingComma: 'all',
    },
  );
}

async function generateSchemas(canonicalSchemas) {
  const schemaEntries = canonicalSchemas
    .map(({ schemaFileName, schema }) => {
      const exportName = schemaFileName
        .replace('.schema.json', '')
        .split('-')
        .map((segment, index) =>
          index === 0
            ? segment
            : `${segment.slice(0, 1).toUpperCase()}${segment.slice(1)}`,
        )
        .join('');
      return `  ${JSON.stringify(exportName)}: ${JSON.stringify(schema, null, 2)},`;
    })
    .join('\n');

  return formatWithPrettier(
    `${generatedHeader}export const protocolV1Schemas = {
${schemaEntries}
} as const;
`,
    {
      parser: 'typescript',
      singleQuote: true,
      trailingComma: 'all',
    },
  );
}

async function assertOrWriteFile(filePath, expectedContents, checkOnly) {
  if (!checkOnly) {
    await mkdir(dirname(filePath), { recursive: true });
    await writeFile(filePath, expectedContents, 'utf8');
    return;
  }

  let actualContents;
  try {
    actualContents = await readFile(filePath, 'utf8');
  } catch (error) {
    throw new Error(
      `WEB.PROTOCOL_GENERATION_DRIFT: generated file is missing: ${filePath}`,
      { cause: error },
    );
  }

  if (actualContents !== expectedContents) {
    throw new Error(
      `WEB.PROTOCOL_GENERATION_DRIFT: regenerate ${filePath} with npm run generate:protocol`,
    );
  }
}

const options = parseArguments(process.argv.slice(2));
const canonicalSchemas = await readCanonicalSchemas();
const generatedTypes = await generateTypes();
const generatedSchemas = await generateSchemas(canonicalSchemas);

await assertOrWriteFile(generatedTypesPath, generatedTypes, options.checkOnly);
await assertOrWriteFile(
  generatedSchemasPath,
  generatedSchemas,
  options.checkOnly,
);

process.stdout.write(
  `${JSON.stringify({
    status: 'passed',
    operation: options.checkOnly
      ? 'protocol-generation-check'
      : 'protocol-generation',
    schema_count: canonicalSchemas.length,
  })}\n`,
);
